# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-09 21:18
from __future__ import unicode_literals

from django.db import migrations

from v1.util.migrations import migrate_page_types_and_fields


def forward_mapper(page_or_revision, data):
    data['sub_heading'] = data.get('body')
    data['large_image'] = data.get('image')
    data['photo'] = data.get('is_overlay')
    data['white_text'] = data.get('is_white_text')
    data['bleed'] = data.get('is_bleeding')
    return data


def forwards(apps, schema_editor):
    page_types_and_fields = [
        ('regulations3k', 'RegulationLandingPage', 'header', 'hero'),
    ]
    migrate_page_types_and_fields(
        apps,
        page_types_and_fields,
        forward_mapper
    )

class Migration(migrations.Migration):

    dependencies = [
        ('regulations3k', '0023_add_new_hero_fields_and_help_text'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
    ]
