# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-07-09 21:22
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('regulations3k', '0024_move_data_to_new_hero_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regulationlandingpage',
            name='header',
            field=wagtail.wagtailcore.fields.StreamField([('hero', wagtail.wagtailcore.blocks.StructBlock([(b'heading', wagtail.wagtailcore.blocks.CharBlock(help_text=b'For complete guidelines on creating heroes, visit our <a href="https://cfpb.github.io/design-manual/global-elements/heroes.html">Design Manual</a>.<ul class="help">Character counts (including spaces) at largest breakpoint:<li>&bull; 41 characters max (one-line heading)</li><li>&bull; 82 characters max (two-line heading)</li></ul>', required=False)), (b'sub_heading', wagtail.wagtailcore.blocks.RichTextBlock(help_text=b'<ul class="help">Character counts (including spaces) at largest breakpoint:<li>&bull; 65-186 characters (after a one-line heading)</li><li>&bull; 108-124 characters (after a two-line heading)</li></ul>', required=False)), (b'large_image', wagtail.wagtailimages.blocks.ImageChooserBlock(help_text=b'When saving illustrations, use a transparent background. <a href="https://github.cfpb.gov/CFPB/hubcap/wiki/Wagtail-image-sizing-guidelines-&-tips">See image dimension guidelines.</a>', required=False)), (b'small_image', wagtail.wagtailimages.blocks.ImageChooserBlock(help_text=b'<b>Optional.</b> No small image required for the standard illustration. <a href="https://github.cfpb.gov/CFPB/hubcap/wiki/Wagtail-image-sizing-guidelines-&-tips">See image dimension guidelines.</a>', required=False)), (b'background_color', wagtail.wagtailcore.blocks.CharBlock(help_text=b'Specify a hex value (with the # sign) from our <a href="http://cfpb.github.io/design-manual/brand-guidelines/color-principles.html">official color palette</a>.', required=False)), (b'photo', wagtail.wagtailcore.blocks.BooleanBlock(help_text=b'<b>Optional.</b> Uses the provided image as a background under the entire hero, creating the "Photo" style of hero (see <a href="https://cfpb.github.io/design-manual/global-elements/heroes.html">Design Manual</a> for details). When using this option, make sure to specify a background color (above) for the left/right margins that appear when screens are wider than 1200px and for the text section when the photo and text stack at mobile sizes.', required=False)), (b'white_text', wagtail.wagtailcore.blocks.BooleanBlock(help_text=b'<b>Optional.</b> Turns the hero text white. Useful if using a dark background color or background image.', required=False)), (b'bleed', wagtail.wagtailcore.blocks.BooleanBlock(help_text=b'<b>Optional.</b> Select if you want the illustration to bleed vertically off the top and bottom of the hero space.', required=False))]))], blank=True),
        ),
    ]
